# Generated by Django 5.0.6 on 2025-01-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'FoodMenu',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'sliderimage',
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_people', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'TableReservation',
            },
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'UserSignup',
            },
        ),
    ]
